auditlogs:
  image:
    tag: main@sha256:fe2e989cc3771640b36bc575bb8840d9968da52a5d310f2d43ddfb01918d790a
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b1d62cfd8cc6a88770ce9a4bfeb89aa12acb6a4da8fd4ba8739fede93dc9c828
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:6a1f47d0a1cda2479ef12335a7737f63051f3e0a8ef55d770d3ec8aa23df35ac
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:053fcff9c90db370be776cb3aa8c6eea763b6814943d665c2df0319dc6889eec
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:c1ed96df3ed7ecf64acb84fae9ae1ed7fefb04b45670b8fac312305ebc8b9188
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:4657130dc731a99144cbda3975ee9bd82345ee79c2292acee83a22b06613464f
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:948c79e4eec8f8f388a7d9def6bafc08e48dda9a010e9d2e010b567644e2b0da
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:8879104c1978698f14f73911cca8dfcd9a76f3c59bbe35ac40122de7bf179ffb
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:7c3961490610dfb8f0f6544ebed5f4ef9b0d7d0e678587f42bd1f8125dc9e9a5
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:84af051e3edbecc9bc585d6a9a9fd5293a1a43f6f331e9381e45ea206773704c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:763db84e973c8de68696eb849c8705dacb6f46a6a02bc977e5ebc160ee7a17b1
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:835652e35c496d8d263348a99d3174bcc1826b1c4fff29ec232d2121bef18658
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:fbba916711699bde53f85d69b681f7918000f246cbb65336c316ce7315d9a864
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:d3ad0c040d29b42075e6051901d9ade296b70464930595e05f56125f54ed3c0e"
    registry: docker.io
    repository: mendersoftware
