auditlogs:
  image:
    tag: main@sha256:ac0dbff562db494b7f90da1ce71e3b37749bdb9c51e1722aa2b098ff28f21160
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:c676a4c72571a19085c6c38b999e93b60fdda8276075afc7d9e3d0b4e98f1284
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:839d351b0026072671bdc0a3254af6f2152a3282f266b34bedfb2c04ed822ead
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:7142186a79c51bc95689f5b5f6ba31bfa2119161ee5929607e739a498255e01a
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:ff270c39a71e8692965dd9e4589988a0401c33cc5f16d93c4f368fa705b81838
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:1f0586c48c6189fdecb19e526d2f730c333c51d42da5bc3b92e634969c633133
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:52facb5127e130312d5eca9ff8825c68275ef411e773a677add298312bd16967
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:a8a31d0e3d7ef568698f07e6db6ac362e865c8303ce72eb9c3f59289a8c5c318
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:3c1c2ec1b0a55c761a9d8e2aad7959e05b880eff2868505b44a40dec67aa96d2
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:2b06ca9fd6a894a03bdcb1dd2dc284c043007aaee3517a5ac2d000f7e4190059
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:39a7e4b1e914dfb80eefe9c43f81c84996952ddf441f3a1e90347a6f48b74d1a
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:00ecde8a4b8ada9ba4adea34e6c5df896c1dced36d6b91754bd5eeb894c09bf9
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:0ed15f0257a734b0e280953699453b4290eee605bedfb9a4cbbc9fe5d51b1b9d
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:32dcb7322b95da56ddddf1a3581a2975d7c14eb4a3fcae537186b330431c7d26"
    registry: registry.mender.io
    repository: mender-server-enterprise
